fullName = input("What is your full name?  ")
adverb = input("adverb of car  ")
noun = input("name of a friend ")
number = input("number of friends ")
nouning = input("noun endding in ing  ")
adjective = input("A smell you hate. ")
verb = input("How you run. ")
adjetive2 = input("How you look when you wake up ")
adjetive3 = input("What is the best color. ")
noun2 = input("Name of room. ")
verb2 = input("input verb. ")
print('It was a ' + adverb + ',cold november day. I woke up to the '+ adjective + ' smell of ' + noun + ' roasting in the '+ noun2 + ' downstairs. I ' + verb + ' down the stairs to see if I could help ' + verb2 + ' the dinner. My mom said,\”see if ' + fullName + ' needs a fresh ' + nouning +  '\". So I carried a tray of glasses full of ' + adjetive3 + ' into the ' + noun2+ ' . When I got there I could belive my ' + adjetive2 + '! There were ' + number + ',' + noun + ' on the floor !')